### PR TITLE
Add README for QA Pipeline

### PR DESCRIPTION
**Pull request by HartS**

### CODE REVIEW

**Comment by HartS** [comment]
This builds on top of https://github.com/SUSE/cf-ci/pull/151 (documented the desired behaviour instead of the needlessly complicated one)

**Comment by greygoo** [comment]
The existing text looks good to me. Could we add some note on how to use the concourse-secrets.gpg? That always made me look though the code in order to find out how to get the credentials working.

**Comment by HartS** [comment]
This is a great suggestion, thanks!

**Comment by HartS** [comment]
Pushed a new commit which addresses this

**Comment by greygoo** [comment]
Looking good now, merging the PR

**Pull request merged**
